name = "gcalc"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "A pure gleam library for mathematical calculations."
licences = ["BSD-3-Clause"]
repository = { type = "github", user = "korbexmachina", repo = "gcalc" }
links = [
# { title = "Website", href = "https://github.com/korbexmachina/gcalc" },
{ title = "Author's website", href = "https://www.korbexmachina.com" },
]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/. 

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
